version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: mysql_course
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: weddb
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_course
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

  backend:
    image: node:18
    container_name: backend_course
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "3000:3000"
    depends_on:
      - mysql